# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_auto_20171107_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='epic_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
