# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_issues_epic_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='timespent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
