# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_issues_timespent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worklog_id', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('start', models.CharField(max_length=30)),
                ('timeSpentSeconds', models.CharField(max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.Issues')),
            ],
        ),
    ]
