# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_worklogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogs',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
