# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_auto_20171225_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogs',
            name='timeSpentSeconds',
            field=models.IntegerField(),
        ),
    ]
