# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0010_remotelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.Issues')),
            ],
        ),
    ]
