# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0012_auto_20171227_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
