# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0013_worker_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PIDLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pid',
            name='labels',
            field=models.ManyToManyField(to='roadmap.PIDLabel'),
        ),
    ]
