# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0015_auto_20180221_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='linked_issues',
            field=models.ManyToManyField(related_name='_issues_linked_issues_+', to='roadmap.Issues'),
        ),
    ]
