# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0017_worker_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cost',
            field=models.FloatField(),
        ),
    ]
