# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0018_auto_20180221_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidlabel',
            name='relevant',
            field=models.BooleanField(default=True),
        ),
    ]
